# Sample usage of reusable.yml in Debug build for backend team
name: CI Test and Debug Pipeline

on:
  push:
    branches:
      - dev
      - feature_pipeline
  pull_request:
    branches:
      - dev
      - feature_pipeline

jobs:
  debug:
    uses: ./.github/workflows/reusable.yml
    with:
      configuration: test-and-debug
      dotnet_version: "9.0.x"
      project_path: CourseProject/CourseProject.csproj
      unit_tests_project_path: UnitTests/UnitTests.csproj
      run_unit_tests: true
      run_static_analysis: false
