name: Build and Deploy Container to Azure

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    secrets:
      REGISTRY_NAME:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      AZURE_WEBAPP_NAME:
        required: true
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

jobs:
  deploy-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        if: ${{ inputs.configuration == 'Release' }}
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/courseproject:${{ github.sha }} .

      - name: Log in to Azure Container Registry
        if: ${{ inputs.configuration == 'Release' }}
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        if: ${{ inputs.configuration == 'Release' }}
        run: docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/courseproject:${{ github.sha }}

      - name: Deploy to Azure Web App
        if: ${{ inputs.configuration == 'Release' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.REGISTRY_NAME }}.azurecr.io/courseproject:${{ github.sha }}
