# Sample usage of reusable.yml in Release build for backend team
# This pipeline runs all the tests made by the QA team and publish the app
name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/reusable.yml
    with:
      configuration: Release
      dotnet_version: "9.0.x"
      project_path: CourseProject/CourseProject.csproj
      unit_tests_project_path: UnitTests/UnitTests.csproj
      run_unit_tests: true
      black_box_tests_project_path: BlackBoxTests/BlackBoxTests.csproj
      run_black_box_tests: false
      reliability_tests_project_path: ReliabilityTests/ReliabilityTests.csproj
      run_reliability_tests: true
      run_static_analysis: true
    secrets:
      APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
